# Generated by Django 6.0.2 on 2026-03-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='can_retake',
            field=models.BooleanField(default=False, verbose_name='Qayta topshirishga ruxsat'),
        ),
    ]
